-- seeds/01_mentees_mentors.sql
-- mentees seeds
INSERT INTO mentees (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Austin', 'King', 'Toronto','austin@gmail.com', '12345', 'https://images.unsplash.com/photo-1624251065173-637a51b95939?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8aW5kaWFuJTIwYm95fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60', 'I have a passion for code!', 'JavaScript, HTML', true);
INSERT INTO mentees (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Kayla', 'Michaels', 'Montréal','kayla@gmail.com', '12345', 'https://images.unsplash.com/photo-1529232356377-57971f020a94?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTl8fGFzaWFuJTIwZ2lybHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60', 'I''ve been learning web development on my own and would some guidance','NodeJS, JavaScript, HTML', true);
INSERT INTO mentees (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Ashley', 'Smith', 'Ottawa','ashley@gmail.com', '12345', 'https://images.unsplash.com/photo-1624610803623-21e434f61180?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8aW5kaWFuJTIwZ2lybHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60', 'Self taught, and looking to learn more about Python','Python, SQL', false);
INSERT INTO mentees (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Josh', 'Richards', 'Toronto','josh@gmail.com', '12345', 'https://images.unsplash.com/photo-1507114845806-0347f6150324?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fGJsYWNrJTIwYm95fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60', 'I''ve been learning Javascript on my own and would love to learn more about React', 'JavaScript, Html, React, PSQL', true);
INSERT INTO mentees (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Louis', 'Coles', 'Calgary','louis@gmail.com', '12345', 'https://images.unsplash.com/flagged/photo-1596479042555-9265a7fa7983?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8dGVlbmFnZSUyMGJveXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60', 'I love to code on my free time!','C++, Python, MongoDB', true);
INSERT INTO mentees (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Bailey', 'Miller', 'London','bailey@gmail.com', '12345', 'https://images.unsplash.com/photo-1599842057874-37393e9342df?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8dGVlbmFnZSUyMGdpcmx8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60', 'I love baking all types of pastries', 'Baking, Food preparation', false);
INSERT INTO mentees (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Mike', 'Williams', 'Toronto','mike@gmail.com', '12345', 'https://images.unsplash.com/photo-1594201510970-f549e4a6e96d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NzR8fHRlZW5hZ2UlMjBib3l8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60', 'I do landscape photography, but am open to other types!', 'Photography, Photoshop, InDesign', false);
INSERT INTO mentees (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Nelson', 'Brown', 'Cairo','nelson@gmail.com', '12345', 'https://images.unsplash.com/photo-1519764622345-23439dd774f7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDh8fGJyb3duJTIwYm95fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60', 'I like to work with clay and make sculptures','Pottery', true);
INSERT INTO mentees (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Nicole', 'Garcia', 'Tokyo','nicole@gmail.com', '12345', 'https://images.unsplash.com/photo-1558539697-96c1032f8c26?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8dGVlbmFnZSUyMGdpcmx8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60', 'I love to cook! My main focus is Asian cuisine','Cooking, Knife skill, isActives, Knowledge of spices and ingredients', true);
INSERT INTO mentees (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Mitchell', 'Jones', 'Ottawa','mitchell@gmail.com', '12345', 'https://images.unsplash.com/photo-1518723276788-e08d67cf8927?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTl8fGJyb3duJTIwYm95fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60', 'I''m a part-time actor interested in photography','Photography, Adobe Illustrator, Acting', true);
INSERT INTO mentees (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Sylvia', 'Davis', 'Milan','sylvia@gmail.com', '12345', 'https://images.unsplash.com/photo-1630539625531-13d781ebb4ee?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NjR8fGJsYWNrJTIwdGVlbmFnZSUyMGdpcmx8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60', 'I''m looking to explore a career in journalism', 'Writing, Digital literacy, Investigative reporting, Research', true);
INSERT INTO mentees (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Skai', 'Rodriguez', 'Detroit','skai@gmail.com', '12345', 'https://images.unsplash.com/photo-1599900554895-5e0fc7bbc9c6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YXNpYW4lMjBnaXJsfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60', 'I''ve been planning small events and would love to expand!','Event planning, Interior design, Budgeting', true);
INSERT INTO mentees (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Ryan', 'Anderson', 'Melbourne','ryan@gmail.com', '12345', 'https://images.unsplash.com/photo-1621388986397-9f0b091e965d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzZ8fHRlZW5hZ2UlMjBib3l8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60', 'I love to work with my hands and build structures','Carpentry, Blueprint drafting, Math', false);
INSERT INTO mentees (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Elliott', 'Jackson', 'Berlin','elliott@gmail.com', '12345', 'https://images.unsplash.com/photo-1507038732509-8b1a9623223a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzB8fGJsYWNrJTIwYm95fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60', 'I paint during my free time and would love to hone this craft', 'Attention to detail, Acryliic paint, Oil paint, Photoshop', true);
INSERT INTO mentees (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Riley', 'Carter', 'Accra','riley@gmail.com', '12345', 'https://images.unsplash.com/photo-1563721573206-bd9a9fb33a37?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fGJsYWNrJTIwdGVlbmFnZSUyMGdpcmx8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60', 'I love solving equations and working with numbers','Math, Data analysis, Programming', true);

-- mentors seeds
INSERT INTO mentors (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Khadija', 'Mohamed', 'Toronto','khadija@gmail.com', '12345', 'https://images.unsplash.com/photo-1648745999279-cb71e69f103d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=910&q=80', 'Student at Lighthouse Labs','React, NodeJS, SQL, Ruby, JavaScript, HTML', true);
INSERT INTO mentors (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Sasu', 'Osayande', 'Toronto','sasu@gmail.com', '12345', 'https://images.unsplash.com/photo-1649389763689-58bfb960e4da?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', 'Student at Lighthouse Labs', 'Ruby, JavaScript, NodeJS, HTML, React, SQL', true);
INSERT INTO mentors (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Carmen', 'Kuang', 'Toronto','carmen@gmail.com', '12345', 'https://images.unsplash.com/photo-1602620470448-ea7ff62ce3ab?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzF8fGJsYWNrJTIwZ2lybHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60', 'Student at Lighthouse Labs', 'JavaScript, HTML, Ruby, NodeJS, React, SQL', true);
INSERT INTO mentors (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Edward', 'Hugh', 'Manila','edward@gmail.com', '12345', 'https://images.unsplash.com/photo-1544168190-79c17527004f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTd8fHByb2Zlc3Npb25hbCUyMG1hbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60', 'I''m a software engineer at Apple', 'Ruby, Python, C++, MongoDB, JavaScript, React', false);
INSERT INTO mentors (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Brad', 'Tyler', 'Halifax','brad@gmail.com', '12345', 'https://images.unsplash.com/photo-1574966740429-6158cb530208?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8cHJvZmVzc2lvbmFsJTIwY2hlZnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60', 'I''ve been working as a chef for 10+ years', 'Asian cuisine, Spanish cuisine, Knife skill, isActives, Food preparation', false);
INSERT INTO mentors (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Joe', 'Jacobs', 'Hong Kong','joe@gmail.com', '12345', 'https://images.unsplash.com/photo-1629186383291-2015c9227a4a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=685&q=80', 'I''ve been coding for 5+ years, and would love to share my knowledge', 'Java, Ruby, Python, React, PSQL', true);
INSERT INTO mentors (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Mary', 'Hodges', 'Istanbul','mary@gmail.com', '12345', 'https://images.unsplash.com/photo-1551180452-aea351b23949?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8YXJ0aXN0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60', 'I''ve been building sculptures for 15+ years', 'Design, Illustration, Procreate, Working with marble', false);
INSERT INTO mentors (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Carl', 'Goodman', 'Montréal','carl@gmail.com', '12345', 'https://images.unsplash.com/photo-1528892952291-009c663ce843?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzN8fHByb2Zlc3Npb25hbCUyMG1hbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60', 'Photographer. I see the world through a lens','Landscape, Portrait, Film, Editorial', true);
INSERT INTO mentors (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Lucas', 'Potter', 'Toronto','lucas@gmail.com', '12345', 'https://images.unsplash.com/photo-1514222709107-a180c68d72b4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDN8fHByb2Zlc3Npb25hbCUyMG1hbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60', 'I''m an accountant and would love to share my knowledge', 'Data Analysis, Math, Accounting softwares', true);
INSERT INTO mentors (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Luna', 'Todd', 'Cairo','luna@gmail.com', '12345', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjB8fHByb2Zlc3Npb25hbCUyMG1hbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60', 'Real Estate Agent for 2+ years', 'Law and regulations, Networking, Technological skill, isActives', true);
INSERT INTO mentors (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Jay', 'Mullins', 'Paris','jay@gmail.com', '12345', 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8cHJvZmVzc2lvbmFsJTIwbWFufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60', 'Employee at Google', 'Ruby, Python', true);
INSERT INTO mentors (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Joseph', 'Wolf', 'Madrid','joseph@gmail.com', '12345', 'https://images.unsplash.com/photo-1581091595283-04de15a05a01?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjR8fGFydGlzdHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60', 'I love designing structures! Maybe you''ve seen my work','Architecture, Design, Math', true);
INSERT INTO mentors (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Erin', 'Franco', 'London','erin@gmail.com', '12345', 'https://images.unsplash.com/photo-1600275669439-14e40452d20b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTl8fHByb2Zlc3Npb25hbCUyMHdvbWFufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60', 'I run my own business centered around promoting sustainability', 'Business, Data anyalsis, Software programs, Management', false);
INSERT INTO mentors (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Miranda', 'Maxwell', 'Miami','miranda@gmail.com', '12345', 'https://images.unsplash.com/photo-1573496129661-bd7fcc7e532b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8ODd8fHByb2Zlc3Npb25hbCUyMHdvbWFufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60', 'Full-time software engineer', 'JavaScript, HTML, Ruby, NodeJS, React, SQL, Python, C++, MongoDB', true);
INSERT INTO mentors (first_name, last_name, location, email, password, photo_url, description, skill, isActive) VALUES ('Hailey', 'Parsons', 'Detroit','hailey@gmail.com', '12345', 'https://images.unsplash.com/photo-1583912268183-a34d41fe464a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8c2NpZW50aXN0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60', 'I''m a scientist studying genetics', 'Microbiology, Research, Study of genes', true);